# Generated by Django 4.1.5 on 2023-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='app.project'),
        ),
    ]
