# Generated by Django 4.1.5 on 2023-01-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.ManyToManyField(blank=True, to='app.project'),
        ),
    ]
